FROM nginx:1.22.0
# WORKDIR /app
# RUN apt update && apt upgrade -y
# RUN apt install php7.4-mysql -y
# RUN apt install php7.4-fpm -y
# RUN service php7.4-fpm start
# COPY ./index.php /usr/share/nginx/html
# RUN rm /usr/share/nginx/html/index.html
# EXPOSE 80

COPY ./default.conf /etc/nginx/conf.d/default.conf